import { Theme } from "styled-system";

import fonts from "./fonts";
import space from "./spaces";
import colors from "./colors";
import breakpoints from "./breakpoints";
import borders from "./borders";
import shadows from "./shadows";
import radii from "./radius";
import zIndices from "./zIndices";

const light: Theme = {
    space,
    ...fonts,
    borders,
    shadows,
    radii,
    zIndices,
    colors: {
        text: {
            primary: colors.gray[900],
            secondary: colors.red[600],
            default: colors.gray[700],
            success: colors.green[600],
            error: colors.red[600],
            warning: colors.yellow[600],
            disabled: colors.gray[400],
            inverse: colors.white,
            white: colors.white,
            link: colors.blue[700],
        },
        bg: {
            primary: colors.gray[900],
            secondary: colors.red[600],
            default: colors.gray[100],
            success: colors.green[500],
            error: colors.red[400],
            warning: colors.yellow[400],
            disabled: colors.gray[200],
            solid: colors.gray[910],
            white: colors.white,
            transparent: colors.transparent,
        },
        border: {
            default: colors.gray[500],
            success: colors.green[500],
            error: colors.red[500],
            warning: colors.yellow[500],
            disabled: colors.gray[400],
            solid: colors.black,
            check: colors.blue[500],
            transparent: colors.transparent,
        },
        button: {
            primary: colors.gray[900],
            secondary: colors.red[600],
            default: colors.gray[200],
            success: colors.green[500],
            error: colors.red[500],
            warning: colors.yellow[500],
            disabled: colors.gray[200],
            transparent: colors.transparent,
            white: colors.white,
        },
        highlight: {
            default: colors.red[600],
            success: colors.green[600],
            error: colors.red[700],
            warning: colors.yellow[600],
            link: colors.red[600],
            check: colors.blue[700],
            light: colors.gray[500],
        },
        avatar: {
            background: colors.gray[300],
            border: colors.gray[400],
        },
        checkbox: {
            default: colors.gray[600],
            error: colors.red[700],
            disabled: colors.gray[200],
        },
        toggle: {
            primary: colors.blue[500],
            secondary: colors.gray[400],
            danger: colors.red[500],
        },
        icon: {
            primary: colors.blue[600],
            secondary: colors.blue[600],
            default: colors.gray[700],
            success: colors.green[500],
            warning: colors.yellow[400],
            error: colors.red[400],
            white: colors.white,
            inverse: colors.gray[600],
            solid: colors.black,
            disabled: colors.gray[500],
            transparent: colors.transparent,
        },
        input: {
            default: colors.gray[100],
            success: colors.green[100],
            error: colors.red[100],
            warning: colors.yellow[100],
            disabled: colors.gray[100],
            dark: colors.grayAlpha[200],
        },
        spinner: {
            primary: colors.white,
            secondary: colors.gray[500],
            outlined: colors.blue[500],
            danger: colors.red[500],
            warning: colors.yellow[500],
        },
        skeleton: {
            start: colors.gray[200],
            transition: colors.gray[400],
            end: colors.gray[200],
        },
        modal: {
            header: colors.gray[100],
            bg: colors.white,
        },
        badge: {
            primary: colors.blue[600],
            secondary: colors.purple[600],
            success: colors.green[600],
            warning: colors.yellow[700],
            danger: colors.red[500],
            default: colors.gray[300],
            white: colors.white,
            dark: colors.gray[900],
        },
        alert: {
            default: colors.blue[200],
            success: colors.green[200],
            error: colors.red[200],
            warning: colors.yellow[200],
        },
        tag: {
            default: colors.blue[200],
            success: colors.green[200],
            error: colors.red[200],
            warning: colors.yellow[200],
        },
        progressBar: {
            primary: colors.blue[500],
            success: colors.green[500],
            danger: colors.red[500],
            warning: colors.yellow[500],
            default: colors.gray[400],
        },
        tab: {
            active: colors.blue[100],
            inactive: colors.gray[200],
            disabled: colors.gray[300],
        },
        countdown: {
            defaultBg: colors.green[200],
            defaultFill: colors.green[600],
            expiringBg: colors.red[200],
            expiringFill: colors.red[600],
        },
        toast: {
            default: colors.blue[100],
            success: colors.green[100],
            error: colors.red[100],
            warning: colors.yellow[100],
            light: colors.white,
            shadow: colors.blackAlpha[100],
        },
        pagination: {
            primary: colors.gray[900],
            disabled: colors.gray[500],
            active: colors.blue[500],
            activeBg: colors.blue[100],
            dots: colors.gray[400],
        },
    },
    breakpoints,
};

const dark: Theme = {
    space,
    ...fonts,
    borders,
    shadows,
    radii,
    zIndices,
    colors: {
        text: {
            primary: colors.gray[200],
            secondary: colors.purple[200],
            tertiary: colors.blue[600],
            disabled: colors.gray[500],
            inverse: colors.white,
            error: colors.red[600],
            success: colors.green[400],
            default: colors.gray[300],
            white: colors.white,
            dark: colors.gray[900],
            link: colors.blue[400],
        },
        bg: {
            primary: colors.gray[900],
            secondary: colors.gray[910],
            tertiary: colors.gray[800],
            quaternary: colors.gray[910],
            outlined: colors.gray[900],
            disabled: colors.gray[900],
            transparent: colors.transparent,
            overlay: colors.blackAlpha[100],
            solid: colors.purple[500],
            white: colors.white,
        },
        border: {
            primary: colors.gray[100],
            secondary: colors.gray[800],
            tertiary: colors.gray[500],
            outlined: colors.gray[800],
            light: colors.gray[700],
            danger: colors.red[400],
            warning: colors.yellow[400],
            solid: colors.gray[600],
            transparent: colors.transparent,
            primaryLight: colors.blue[200],
            secondaryLight: colors.purple[100],
            successLight: colors.green[300],
            warningLight: colors.yellow[200],
            dangerLight: colors.red[200],
        },
        button: {
            default: colors.blue[600],
            outlined: colors.gray[910],
            secondary: colors.purple[600],
            success: colors.green[600],
            danger: colors.red[600],
            disabled: colors.gray[700],
            transparent: colors.transparent,
        },
        highlight: {
            primary: colors.blue[500],
            primaryOutlined: colors.blue[100],
            secondary: colors.purple[500],
            tertiary: colors.blue[600],
            quaternary: colors.blue[400],
            quinary: colors.blue[100],
            senary: colors.gray[400],
            outlined: colors.gray[800],
            success: colors.green[500],
            danger: colors.red[500],
            dangerOutlined: colors.gray[700],
            warningOutlined: colors.gray[700],
            link: colors.purple[300],
            error: colors.redAlpha[200],
        },
        avatar: {
            background: colors.gray[300],
            border: colors.gray[400],
        },
        toggle: {
            primary: colors.blue[500],
            secondary: colors.gray[400],
            danger: colors.red[500],
        },
        icon: {
            primary: colors.blue[400],
            secondary: colors.gray[300],
            tertiary: colors.white,
            quaternary: colors.gray[900],
            fill: colors.white,
            bgFill: colors.gray[900],
            inverse: colors.white,
            solid: colors.white,
            light: colors.blue[400],
            disabled: colors.gray[500],
            transparent: colors.transparent,
            success: colors.green[500],
            warning: colors.yellow[600],
            danger: colors.red[500],
        },
        status: {
            primary: colors.gray[200],
            secondary: colors.gray[400],
            success: colors.green[400],
            error: colors.red[400],
            warning: colors.yellow[500],
        },
        spinner: {
            primary: colors.white,
            secondary: colors.gray[400],
            outlined: colors.blue[500],
            danger: colors.red[400],
            warning: colors.yellow[400],
        },
        skeleton: {
            start: colors.gray[700],
            transition: colors.gray[900],
            end: colors.gray[700],
        },
        modal: {
            header: colors.blackAlpha[100],
            bg: colors.gray[910],
        },
        badge: {
            primary: colors.blue[600],
            secondary: colors.purple[600],
            success: colors.green[600],
            warning: colors.yellow[700],
            danger: colors.red[500],
            default: colors.gray[300],
            white: colors.white,
            dark: colors.gray[900],
        },
        alert: {
            info: colors.blueAlpha[100],
            warning: colors.yellowAlpha[100],
            success: colors.greenAlpha[100],
            danger: colors.redAlpha[500],
        },
        tag: {
            primary: colors.blueAlpha[100],
            secondary: colors.purpleAlpha[100],
            success: colors.greenAlpha[100],
            warning: colors.yellowAlpha[100],
            danger: colors.redAlpha[500],
            default: colors.grayAlpha[200],
            dark: colors.grayAlpha[800],
        },
        progressBar: {
            primary: colors.blue[500],
            success: colors.green[500],
            danger: colors.red[500],
            warning: colors.yellow[500],
            default: colors.gray[700],
        },
        tab: {
            active: colors.blueAlpha[100],
            inactive: colors.grayAlpha[200],
            disabled: colors.grayAlpha[300],
        },
        countdown: {
            defaultBg: colors.green[200],
            defaultFill: colors.green[600],
            expiringBg: colors.red[200],
            expiringFill: colors.red[600],
        },
        toast: {
            bgInfo: colors.gray[900],
            bgSuccess: colors.gray[900],
            bgError: colors.gray[900],
            bgWarning: colors.gray[900],
            bgLight: colors.gray[900],
            borderInfo: colors.blue[500],
            borderSuccess: colors.green[500],
            borderError: colors.red[500],
            borderWarning: colors.yellow[500],
            borderLight: colors.white,
            shadow: colors.blackAlpha[100],
        },
        pagination: {
            primary: colors.gray[100],
            disabled: colors.gray[500],
            active: colors.blue[500],
            activeBg: colors.blue[100],
            dots: colors.gray[600],
        },
    },
    breakpoints,
};

export default { light, dark };
